name: Build and Deploy Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"
        
    - name: Install dependencies
      run: |
        pip install -e .

    - name: Build Documentation
      run: |
        sphinx-build -b html docs/ docs/build/

    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Deploy to gh-pages
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -f docs/build/
        git commit -m "Auto update docs"
        git push
